name: Haskell CI

on: [push, pull_request]

jobs:
  cabal:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        plan:
          - ghc: '8.8.4'

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.plan.allow-fail == true }}

    steps:
    - uses: actions/checkout@v3
      
    - uses: haskell/actions/setup@v2
      id: cabal-setup-haskell
      with:
        ghc-version: ${{ matrix.plan.ghc }}

    - uses: jorelali/setup-elm@v3
      with:
        elm-version: 0.19.1

    - name: Configure and freeze
      run: |
        set -ex
        cabal v2-update
        cabal v2-configure --enable-tests --enable-benchmarks --test-show-details=streaming
        cat cabal.project.freeze

    - uses: actions/cache@v3
      with:
        path: ${{ steps.cabal-setup-haskell.outputs.cabal-store }}
        key: ${{ runner.os }}-cabal-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          ${{ runner.os }}-cabal-

    - name: Install dependencies
      run: cabal v2-build --only-dependencies all
    - name: Build Haskell
      run: cabal v2-build all
    - name: Haddock
      run: cabal v2-haddock all
    - name: Build Elm
      run: make frontend
    - name: Test
      run: make test
