name: Haskell CI

on: [push, pull_request]

jobs:
  cabal:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        plan:
          - ghc: '8.8.4'

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.plan.allow-fail == true }}
    env:
      FREEZE: ${{ matrix.plan.freeze }}

    steps:
    - uses: actions/checkout@v2
      
    - uses: haskell/actions/setup@v1
      id: cabal-setup-haskell
      with:
        ghc-version: ${{ matrix.plan.ghc }}

    - name: Configure and freeze
      run: |
        set -ex
        rm -f cabal.project.freeze
        cabal v2-update
        cabal v2-configure --enable-tests --enable-benchmarks --test-show-details=streaming
        if [ "x" == "x$FREEZE" ]; then cabal v2-freeze; else cp freezes/$FREEZE cabal.project.freeze; fi
        cat cabal.project.freeze

    - uses: actions/cache@v2
      with:
        path: ${{ steps.cabal-setup-haskell.outputs.cabal-store }}
        key: ${{ runner.os }}-cabal-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          ${{ runner.os }}-cabal-

    - name: Install dependencies
      run: cabal v2-build --only-dependencies all
    - name: Build
      run: cabal v2-build all
    - name: Haddock
      run: cabal v2-haddock all
    - name: Test
      run: cabal v2-test --jobs=1 all
